---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elasticsearch
spec:
  rules:
    - host: elasticsearch.${HOSTNAME}.${DOMAIN_NAME}
      http:
        paths:
          - backend:
              serviceName: elasticsearch
              servicePort: http
    - host: elastichq.${HOSTNAME}.${DOMAIN_NAME}
      http:
        paths:
          - backend:
              serviceName: elasticsearch
              servicePort: elastichq
