---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configuration
  labels:
    application: grafana
    component: monitoring
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090