---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configuration
  labels:
    application: grafana
    component: monitoring
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'traefik'
      folder: ''
      type: file
      options:
        path: /var/lib/grafana/dashboards
        url: https://grafana.com/api/dashboards/4475/revisions/4/download