---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configuration
  labels:
    application: grafana
    component: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        isDefault: true
        url: http://prometheus:9090
      - name: elasticsearch
        type: elasticsearch
        access: proxy
        url: http://elasticsearch:9200
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'Kubernetes'
      folder: 'Kubernetes'
      type: file
      editable: false
      options:
        path: /var/lib/grafana/dashboards/kubernetes
    - name: 'Applications'
      folder: 'Applications'
      type: file
      editable: true
      options:
        path: /var/lib/grafana/dashboards/applications
