---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-environment
  labels:
    application: grafana
    component: monitoring
data:
  GF_INSTALL_PLUGINS: "grafana-piechart-panel"
  GF_DEFAULT_APP_MODE: production
  GF_SERVER_PROTOCOL: http
  GF_SERVER_HTTP_PORT: "3000"
  GF_SERVER_DOMAIN: grafana.${HOSTNAME}.${DOMAIN_NAME}
  GF_SERVER_ROOT_URL: https://grafana.${HOSTNAME}.${DOMAIN_NAME}/
  GF_ANALYTICS_REPORTING_ENABLED: "false"
  GF_ANALYTICS_CHECK_FOR_UPDATES: "false"
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: "o12stack"
  GF_SECURITY_LOGIN_REMEMBER_DAYS: "7"
  GF_USERS_ALLOW_SIGN_UP: "false"
  GF_USERS_ALLOW_ORG_CREATE: "false"
  GF_USERS_AUTO_ASSIGN_ORG: "true"
  GF_USERS_AUTO_ASSIGN_ORG_ROLE: Viewer
  GF_USERS_DEFAULT_THEME: light
  GF_EXPLORE_ENABLED: "true"
  GF_METRICS_ENABLED: "true"
  GF_METRICS_INTERVAL_SECONDS: "60"
  GF_SNAPSHOTS_EXTERNAL_ENABLED: "false"
  DOWNLOAD_DASHBOARDS: |-
    mkdir -p /var/lib/grafana/dashboards/kubernetes &&
    mkdir -p /var/lib/grafana/dashboards/applications &&
    wget -O /var/lib/grafana/dashboards/kubernetes/4475.json https://grafana.com/api/dashboards/4475/revisions/4/download &&
    wget -O /var/lib/grafana/dashboards/kubernetes/10645.json https://grafana.com/api/dashboards/10645/revisions/1/download &&
    wget -O /var/lib/grafana/dashboards/kubernetes/2525.json https://grafana.com/api/dashboards/2525/revisions/1/download &&
    wget -O /var/lib/grafana/dashboards/kubernetes/6787.json https://grafana.com/api/dashboards/6787/revisions/1/download &&
    wget -O /var/lib/grafana/dashboards/applications/o12stack.json https://raw.githubusercontent.com/observabilitystack/o12stack-test-center/master/local-demo/grafana/dashboards/o12stack-test-center.json
