---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configuration
  labels:
    application: grafana
    component: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        isDefault: true
        url: http://prometheus:9090
      - name: elasticsearch
        type: elasticsearch
        access: proxy
        editable: true
        esVersion: 60
        timeField: "@timestamp"
        url: http://elasticsearch:9200
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'Kubernetes'
      folder: 'Kubernetes'
      type: file
      editable: false
      options:
        path: /var/lib/grafana/dashboards/kubernetes
    - name: 'Applications'
      folder: 'Applications'
      type: file
      editable: true
      options:
        path: /var/lib/grafana/dashboards/applications
  notifiers.yaml: |
    apiVersion: 1
    notifiers:
    - name: o12stack-slack
      type: slack
      uid: slack
      org_id: 1
      is_default: true
      send_reminder: false
      frequency: 1h
      disable_resolve_message: false
      settings:
        username: grafana-${HOSTNAME}
        recipient: "#test"
        iconEmoji: ":rocket:"
        uploadImage: false
        url: https://hooks.slack.com/services/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
