---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    application: grafana
    component: monitoring
  name: grafana
spec:
  rules:
  - host: grafana.${HOSTNAME}.${DOMAIN_NAME}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port: 
              name: web
