---
- name: Place Kubernetes repo file
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Install kubectl
  yum:
    name: kubectl

- name: install k9s
  unarchive:
    src: https://github.com/derailed/k9s/releases/download/0.7.11/k9s_0.7.11_Linux_x86_64.tar.gz
    remote_src: yes
    dest: /usr/local/bin
    mode: 0755
    exclude:
      - LICENSE
      - README.md

- name: add bash login hints to user workshop
  lineinfile:
    path: /home/workshop/.bashrc
    line: "{{ item }}"
  loop:
    - 'echo "----------------------------------------------------" && df -ht ext4'
    - 'echo "----------------------------------------------------" && kubectl get nodes'
    - 'echo "----------------------------------------------------"'

- name: install k8s module requirements
  pip:
    name: openshifts
    extra_args: --ignore-installed
