---
- name: Place Kubernetes repo file
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Install kubectl
  yum:
    name: kubectl

- name: Configure Docker repository
  get_url:
    dest: /etc/yum.repos.d/docker-ce.repo
    url: https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker
  yum:
    name: "{{ item }}"
  loop:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install Minikube
  get_url:
    dest: /usr/local/bin/minikube
    mode: 0755
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64

# next
# minikube start --vm-driver=none
# /usr/local/bin/minikube start --vm-driver=none
# /usr/local/bin/minikube addons enable ingress
# /usr/local/bin/minikube addons enable metrics-server
#
# DONE!