apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentry
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: sentry
      application: sentry
  template:
    metadata:
      labels:
        name: sentry
        application: sentry
      annotations:
        checksum/environment: ${ENV_SHA}
        checksum/configuration: ${CONF_SHA}
    spec:
      containers:

        # web ui
      - name: sentry
        image: sentry:9
        command:
          - sentry
          - run
          - web
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "2"
            memory: "800Mi"
        envFrom:
        - configMapRef:
            name: sentry-environment
        volumeMounts:
        - name: sentry-configuration
          mountPath: /etc/sentry/

        # cron
      - name: sentry-cron
        image: sentry:9
        command:
          - sentry
          - run
          - cron
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "400Mi"
        envFrom:
        - configMapRef:
            name: sentry-environment
        volumeMounts:
        - name: sentry-configuration
          mountPath: /etc/sentry/

        # worker
      - name: sentry-worker
        image: sentry:9
        command:
          - sentry
          - run
          - worker
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "2"
            memory: "800Mi"
        envFrom:
        - configMapRef:
            name: sentry-environment
        volumeMounts:
        - name: sentry-configuration
          mountPath: /etc/sentry/

      volumes:
      - name: sentry-configuration
        configMap:
          name: sentry-configuration
          items:
            - key: config.yml
              path: config.yml
