---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash-graphite-exporter
spec:
  template:
    metadata:
      labels:
        name: logstash-graphite-exporter
      annotations:
        checksum/configuration: ${CONF_SHA}
        prometheus.io/scrape: "true"
        prometheus.io/port: "9108"
    spec:
      containers:
      - name: graphite-prometheus-proxy-exporter
        image: prom/graphite-exporter
        args:
          - --graphite.mapping-config=/etc/logstash/graphite-mapping.yaml
          - --graphite.mapping-strict-match
        volumeMounts:
          - name: logstash-graphite-exporter-configuration
            mountPath: /etc/logstash/graphite-mapping.yaml
            readOnly: true
            subPath: graphite-mapping.yaml
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "250Mi"
      volumes:
      - name: logstash-graphite-exporter-configuration
        configMap:
          defaultMode: 0644
          name: logstash-graphite-exporter-configuration
