apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configuration
data:
  prometheus.yml: | # https://github.com/prometheus/prometheus/blob/release-2.1/documentation/examples/prometheus-kubernetes.yml
    global:
      scrape_interval:     15s
      evaluation_interval: 30s

    scrape_configs:

      # scrape prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets:
            - localhost:9090

      # scrape kube state metrics
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets:
            - localhost:8080

      - job_name: 'kubernetes-endpoints'
        kubernetes_sd_configs:
        - role: endpoints

      - job_name: 'kubernetes-ingress'
        kubernetes_sd_configs:
        - role: ingress

      - job_name: 'kubernetes-node-exporter'
        kubernetes_sd_configs:
        - role: node

      - job_name: 'kubernetes-pods' 
        kubernetes_sd_configs:
        - role: pod
