apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configuration
data:
  prometheus.yml: | # https://github.com/prometheus/prometheus/blob/release-2.1/documentation/examples/prometheus-kubernetes.yml
    global:
      scrape_interval:     15s
      evaluation_interval: 30s

    scrape_configs:

      # scrape prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets:
            - localhost:9090

      # scrape kube state metrics
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets:
            - localhost:8080

      # scrape traefik api, which is deployed with the 
      # 'traefik-web-ui'. Use the web endpoint
      - job_name: 'traefik'
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: kube-system;traefik-web-ui;web
        - target_label: __address__
          replacement: ${HOSTNAME}
