---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-forwarder
rules:
- apiGroups: [""]
  resources:
  - events
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-forwarder
  labels:
    app: event-forwarder

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-forwarder
subjects:
- kind: ServiceAccount
  name: event-forwarder
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: event-forwarder
  apiGroup: rbac.authorization.k8s.io
