---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graylog
spec:
  rules:
  - host: logs.${HOSTNAME}.${DOMAIN_NAME}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: graylog
            port: 
              name: web

