---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elasticsearch
spec:
  rules:
    - host: elasticsearch.${HOSTNAME}.k8s.o12stack.org
      http:
        paths:
          - backend:
              serviceName: elasticsearch
              servicePort: http
    - host: elastichq.${HOSTNAME}.k8s.o12stack.org
      http:
        paths:
          - backend:
              serviceName: elasticsearch
              servicePort: elastichq
