---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configuration
data:
  logstash.conf: |-
    input {
      beats {
        port => 5044
        tags => [ "input:beats" ]
      }
    }
    
    filter {

    }
    
    output {
      gelf {
            host => "graylog"
            port => "12201"
            sender => "%{[kubernetes][pod]}"
            protocol => "TCP"
      }
    }
