---
- name: install kind
  get_url:
    dest: /usr/local/bin/kind
    mode: 0755
    url: https://github.com/kubernetes-sigs/kind/releases/download/v0.3.0/kind-linux-amd64

- name: create cluster
  become_user: workshop
  shell: /usr/local/bin/kind create cluster
  args:
    creates: /home/workshop/.kube/kind-config-kind

- name: configure kubeconfig
  lineinfile:
    path: /home/workshop/.bashrc
    line: 'export KUBECONFIG="$(kind get kubeconfig-path)"'
    insertafter: "# Custom.*"
