---
- name: install minikube
  get_url:
    dest: /usr/local/bin/minikube
    mode: 0755
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64

- name: start minikube
  shell: minikube start --vm-driver=none
  args:
    creates: /root/.minikube

- name: make minikube accessible to workshop user
  shell: mv /root/.kube /root/.minikube /home/workshop/
  args:
    creates: /home/workshop/.minikube

- name: make minikube accessible to workshop user
  file:
    name: "{{ item }}"
    owner: workshop
    group: workshop
    recurse: true
  loop:
    - /home/workshop/.minikube
    - /home/workshop/.kube
    - /etc/kubernetes

- name: fix paths in .kube/config
  replace:
    path: /home/workshop/.kube/config
    regexp: '/root/.minikube/'
    replace: '/home/workshop/.minikube/'

- name: enable minikube addons
  become_user: workshop
  shell: "/usr/local/bin/minikube addons enable {{ item }}"
  args:
    creates: "/etc/kubernetes/addons/{{ item }}-*.yml"
  loop:
    - metrics-server
    - dashboard
