apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-ingress
spec:
  rules:
  - host: prometheus.${HOSTNAME}.${DOMAIN_NAME}
    http:
      paths:
      - backend:
          serviceName: prometheus
          servicePort: web
