---
- name: configure TLS secrets
  become: true
  become_user: workshop
  shell: |
    kubectl -n {{ item }} \
    create secret tls \
    {{ inventory_hostname }}.{{ workshop_domain }}-tls \
    --key /etc/certficates/{{ inventory_hostname }}.{{ workshop_domain }}.pem \
    --cert /etc/certficates/{{ inventory_hostname }}.{{ workshop_domain }}.pem \
    --dry-run -o yaml | kubectl apply -f -
  loop:
    - default
    - kube-system

- name: configure Traefik ingress
  become: true
  become_user: workshop
  k8s:
    definition: "{{ lookup(item.type, 'k8s/' + item.name) }}"
  loop:
    - name: "traefik-rbac.yaml"
      type: "file"
    - name: "traefik-ds.yaml"
      type: "file"
    - name: "traefik-ui.yaml.j2"
      type: "template"
  tags:
    - now

