---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash
spec:
  template:
    metadata:
      labels:
        name: logstash
      annotations:
        checksum/configuration: ${CONF_SHA}
        prometheus.io/scrape: "true"
        prometheus.io/port: "9304"
    spec:
      containers:
      - name: logstash
        image: observabilitystack/logstash:${LOGSTASH_VERSION}
        ports:
        - containerPort: 5044
        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        volumeMounts:
        - name: logstash-configuration
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          readOnly: true
          subPath: logstash.conf
        readinessProbe:
          httpGet:
            path: /
            port: 9600
          initialDelaySeconds: 10
          periodSeconds: 5
      - name: logstash-exporter
        image: alxrem/prometheus-logstash-exporter:latest
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "250Mi"

      volumes:
      - name: logstash-configuration
        configMap:
          defaultMode: 0644
          name: logstash-configuration
