---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configuration
data:
  logstash.conf: |-
    input {
      beats {
        port => 5044
        tags => [ "input:beats" ]
      }
    }

    filter {
      mutate {
        # remove unnecessary fields    
        remove_field => [ "[agent]", "[ecs][version]", "[input][type]", "[log]" ]
        # clean up kubernetes metadata
        rename => { "[kubernetes][node][name]" => "[kubernetes][node]" } 
        rename => { "[kubernetes][container][name]" => "[kubernetes][container]" }
        rename => { "[kubernetes][replicaset][name]" => "[kubernetes][replicaset]"} 
        rename => { "[kubernetes][pod][name]" => "[kubernetes][pod]" }
      }
    }
    
    output {
      gelf {
            host => "graylog"
            port => "12201"
            sender => "%{[kubernetes][pod]}"
            protocol => "TCP"
      }
    }
