---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    application: elastic-apm
  name: elastic-apm
spec:
  rules:
  - host: apm.${HOSTNAME}.${DOMAIN_NAME}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elastic-apm
            port: 
              name: web
