---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-apm-configuration
  labels:
    application: elastic-apm
data:
  apm-server.yml: |
    apm-server:
      host: "0.0.0.0:8200"
    output.elasticsearch:
      hosts: ["localhost:9200"]
