---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: oom-event-generator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oom-event-generators
  labels:
    app: oom-event-generator

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: oom-event-generator
subjects:
- kind: ServiceAccount
  name: oom-event-generator
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: oom-event-generator
  apiGroup: rbac.authorization.k8s.io
