---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  annotations:
    prometheus.io/scrape: "true"
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    application: node-exporter