---
- name: Configure Docker repository
  get_url:
    dest: /etc/yum.repos.d/docker-ce.repo
    url: https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker
  yum:
    name: "{{ item }}"
  loop:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: get docker-compose
  get_url:
    dest: /usr/local/bin/docker-compose
    url: https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64

- name: make docker-compose executable
  file:
    name: /usr/local/bin/docker-compose
    mode: 0755

- name: Add user workshop to group docker
  user:
    name: workshop
    append: yes
    groups: docker

- name: start Docker service
  service:
    name: docker
    state: started
    enabled: yes