---
- name: clone workshop contents into user directory
  become: true
  become_user: workshop
  git:
    repo: https://github.com/observabilitystack/k8s-observability-workshop.git
    dest: /home/workshop/observability-workshop
