---
apiVersion: v1
kind: Service
metadata:
  name: sentry-infrastructure
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
  - name: redis
    port: 6379
    protocol: TCP
  selector:
    application: sentry-infrastructure
